package cn.clxy.game.tetris.view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;

import cn.clxy.game.tetris.model.Block;
import cn.clxy.game.tetris.model.Theme;

/**
 * Show next block.
 * @author clxy
 */
public class BlockPanel extends javax.swing.JPanel {

    private Block block;

    /**
     * Creates new form BlockPanel.
     */
    public BlockPanel() {

        initComponents();
        setPreferredSize(ViewUtil.translate(Theme.getMaxTetrisSize()));
    }

    public Block getBlock() {
        return block;
    }

    public void setBlock(Block block) {

        this.block = block;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {

        super.paintComponent(g);

        if (block == null) {
            return;
        }

        int dw = Theme.DOT_SIZE.width;
        int dh = Theme.DOT_SIZE.height;

        // Make it center.
        int width = getWidth();
        int height = getHeight();

        Dimension bs = ViewUtil.translate(block.getSize());
        int x = (width - bs.width * dw) / 2;
        int y = (height - bs.height * dh) / 2;

        ViewUtil.drawTetris(g, block, ViewUtil.Draws.Image, new Point(x / dw, y / dh));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private static final long serialVersionUID = 1L;
}
