package cn.clxy.game.tetris.view;

/**
 * @author clxy
 */
public class SinglePanel extends ImagePanel {

    /** Creates new form SinglePanel */
    public SinglePanel() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.awt.GridBagConstraints gridBagConstraints;

        stackPanel = new StackPanel();
        blockPanel = new BlockPanel();
        scorePanel = new ScorePanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        stackPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stackPanel.setMinimumSize(new java.awt.Dimension(150, 200));
        stackPanel.setName("stackPanel"); // NOI18N
        stackPanel.setOpaque(false);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(stackPanel, gridBagConstraints);

        blockPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        blockPanel.setMinimumSize(new java.awt.Dimension(150, 80));
        blockPanel.setName("blockPanel"); // NOI18N
        blockPanel.setOpaque(false);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(blockPanel, gridBagConstraints);

        scorePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scorePanel.setMinimumSize(new java.awt.Dimension(150, 120));
        scorePanel.setName("scorePanel"); // NOI18N
        scorePanel.setOpaque(false);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(scorePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cn.clxy.game.tetris.view.BlockPanel blockPanel;
    private cn.clxy.game.tetris.view.ScorePanel scorePanel;
    private cn.clxy.game.tetris.view.StackPanel stackPanel;

    // End of variables declaration//GEN-END:variables

    public BlockPanel getBlockPanel() {
        return blockPanel;
    }

    public ScorePanel getScorePanel() {
        return scorePanel;
    }

    public StackPanel getStackPanel() {
        return stackPanel;
    }

    private static final long serialVersionUID = 1L;
}
