/*
 */

/*
 * StackPanel.java
 *
 * Created on Jun 20, 2009, 10:51:58 AM
 */

package cn.clxy.game.tetris.view;

import java.awt.Graphics;

import cn.clxy.game.tetris.model.Block;
import cn.clxy.game.tetris.model.Stack;
import cn.clxy.game.tetris.model.Theme;
import cn.clxy.game.tetris.view.ViewUtil.Draws;

/**
 * @author clxy
 */
public class StackPanel extends javax.swing.JPanel {

    private Stack stack;
    private Block block;
    private Block shadow;

    /** Creates new form StackPanel */
    public StackPanel() {
        initComponents();
        setPreferredSize(ViewUtil.translate(Theme.getStackSize()));
    }

    @Override
    protected void paintComponent(Graphics g) {

        super.paintComponent(g);

        ViewUtil.drawTetris(g, stack, Draws.Image);
        ViewUtil.drawTetris(g, block, Draws.Image);
        ViewUtil.drawTetris(g, shadow, Draws.Shadow);
    }

    public Stack getStack() {
        return stack;
    }

    public void setStack(Stack stack) {

        this.stack = stack;
        repaint();
    }

    public Block getBlock() {
        return block;
    }

    public void setBlock(Block block) {
        this.block = block;
        repaint();
    }

    public Block getShadow() {
        return shadow;
    }

    public void setShadow(Block shadow) {
        this.shadow = shadow;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private static final long serialVersionUID = 1L;
}
