package cn.clxy.tools.webdriver.ui;

import java.util.ArrayList;
import java.util.List;

import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;

import cn.clxy.tools.webdriver.model.Account;
import cn.clxy.tools.webdriver.service.AppService;

/**
 * @author clxy
 */
public class AccountDialog extends javax.swing.JDialog {

    private Account current = null;
    private Account result = null;
    private List<Account> list = new ArrayList<Account>();
    private AppService service = new AppService();
    private BindingGroup accountGroup;
    private BindingGroup tableGroup;

    /** Creates new form AccountDialog */
    public AccountDialog(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();

        List<Account> accounts = service.getAccounts();
        /*
         * tableGroup.unbind(); list.clear(); list.addAll(accounts); tableGroup.bind();
         */}

    public Account getAccount() {
        return result;
    }

    @Action
    public void add() {

        current = new Account();
    }

    @Action
    public void delete() {

        int selected = accountTable.getSelectedRow();
        if (selected == -1) {
            return;
        }

        // Remove from UI

        // save.
        service.saveAccount(list);
    }

    @Action
    public void save() {

        list.add(current);
        service.saveAccount(list);
    }

    @Action
    public void apply() {
        result = current;
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        splitPane = new javax.swing.JSplitPane();
        listPanel = new javax.swing.JPanel();
        connLabel = new javax.swing.JLabel();
        buttonsPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        editPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        useridLabel = new javax.swing.JLabel();
        useridTextField = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        localLabel = new javax.swing.JLabel();
        localTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        urlLabel = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        buttonPanel2 = new javax.swing.JPanel();
        applyButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        splitPane.setDividerLocation(300);
        splitPane.setName("splitPane"); // NOI18N

        listPanel.setName("listPanel"); // NOI18N
        listPanel.setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
                .getInstance(cn.clxy.tools.webdriver.App.class).getContext().getResourceMap(
                        AccountDialog.class);
        connLabel.setText(resourceMap.getString("connLabel.text")); // NOI18N
        connLabel.setName("connLabel"); // NOI18N
        listPanel.add(connLabel, java.awt.BorderLayout.PAGE_START);

        buttonsPanel1.setName("buttonsPanel1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(
                cn.clxy.tools.webdriver.App.class).getContext().getActionMap(AccountDialog.class,
                this);
        addButton.setAction(actionMap.get("add")); // NOI18N
        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setName("addButton"); // NOI18N
        buttonsPanel1.add(addButton);

        deleteButton.setAction(actionMap.get("delete")); // NOI18N
        deleteButton.setText(resourceMap.getString("deleteButton.text")); // NOI18N
        deleteButton.setName("deleteButton"); // NOI18N
        buttonsPanel1.add(deleteButton);

        listPanel.add(buttonsPanel1, java.awt.BorderLayout.PAGE_END);

        tableScrollPane.setName("tableScrollPane"); // NOI18N

        accountTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
                { null, null, null }, { null, null, null }, { null, null, null } }, new String[] {
                "Name", "URL", "Local" }) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class,
                    java.lang.String.class };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        accountTable.setName("accountTable"); // NOI18N
        tableScrollPane.setViewportView(accountTable);

        listPanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        splitPane.setLeftComponent(listPanel);

        editPanel.setName("editPanel"); // NOI18N
        editPanel.setLayout(new java.awt.GridBagLayout());

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N
        nameLabel.setPreferredSize(new java.awt.Dimension(90, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(nameLabel, gridBagConstraints);

        nameTextField.setName("nameTextField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(nameTextField, gridBagConstraints);

        useridLabel.setText(resourceMap.getString("useridLabel.text")); // NOI18N
        useridLabel.setName("useridLabel"); // NOI18N
        useridLabel.setPreferredSize(new java.awt.Dimension(80, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(useridLabel, gridBagConstraints);

        useridTextField.setText(resourceMap.getString("useridTextField.text")); // NOI18N
        useridTextField.setName("useridTextField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(useridTextField, gridBagConstraints);

        pwdLabel.setText(resourceMap.getString("pwdLabel.text")); // NOI18N
        pwdLabel.setName("pwdLabel"); // NOI18N
        pwdLabel.setPreferredSize(new java.awt.Dimension(27, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(pwdLabel, gridBagConstraints);

        pwdTextField.setText(resourceMap.getString("pwdTextField.text")); // NOI18N
        pwdTextField.setName("pwdTextField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(pwdTextField, gridBagConstraints);

        localLabel.setText(resourceMap.getString("localLabel.text")); // NOI18N
        localLabel.setName("localLabel"); // NOI18N
        localLabel.setPreferredSize(new java.awt.Dimension(27, 16));
        localLabel.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(localLabel, gridBagConstraints);

        localTextField.setText(resourceMap.getString("localTextField.text")); // NOI18N
        localTextField.setName("localTextField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(localTextField, gridBagConstraints);

        browseButton.setText(resourceMap.getString("browseButton.text")); // NOI18N
        browseButton.setName("browseButton"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(browseButton, gridBagConstraints);

        urlLabel.setText(resourceMap.getString("urlLabel.text")); // NOI18N
        urlLabel.setName("urlLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(urlLabel, gridBagConstraints);

        urlTextField.setText(resourceMap.getString("urlTextField.text")); // NOI18N
        urlTextField.setName("urlTextField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        editPanel.add(urlTextField, gridBagConstraints);

        buttonPanel2.setName("buttonPanel2"); // NOI18N
        buttonPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        applyButton.setAction(actionMap.get("apply")); // NOI18N
        applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N
        buttonPanel2.add(applyButton);

        saveButton.setAction(actionMap.get("save")); // NOI18N
        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N
        buttonPanel2.add(saveButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        editPanel.add(buttonPanel2, gridBagConstraints);

        splitPane.setRightComponent(editPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountTable;
    private javax.swing.JButton addButton;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton browseButton;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JPanel buttonsPanel1;
    private javax.swing.JLabel connLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel listPanel;
    private javax.swing.JLabel localLabel;
    private javax.swing.JTextField localTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JLabel useridLabel;
    private javax.swing.JTextField useridTextField;
    // End of variables declaration//GEN-END:variables

    private static final long serialVersionUID = 1L;

    private void bindAccount() {

        accountGroup = new BindingGroup();
        AutoBinding finished = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, current,
                BeanProperty.create("name"), nameTextField, BeanProperty.create("text"));
        accountGroup.addBinding(finished);

        accountGroup.bind();
    }

    private void bindTable() {
    }
}
